Repository jenkins-infra/plugin-modernizer-tool, pull requests merged in 2024-06, with the labels that each got.

#9 Add MIT License
  LICENSE
  pom.xml
Labels: documentation

#19 Reorganize dependencies
  plugin-modernizer-cli/pom.xml
  plugin-modernizer-core/pom.xml
  pom.xml
Labels: dependencies, chore

#29 Add log discriminator to separate log file when modernized plugin
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/ConsoleLogFilter.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/PluginLoggerDiscriminator.java
  plugin-modernizer-cli/src/main/resources/logback.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/MavenInvoker.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
Labels: enhancement

#31 Missing CODEOWNER for PR reviews
  .github/CODEOWNERS
Labels: chore

#37 Upgrade jackson and use bom
  pom.xml
Labels: dependencies, chore

#38 Add warning to avoid opening issue during GSoC 2024
  README.md
Labels: documentation

#39 Reference `AddCodeOwner`existing recipe
  plugin-modernizer-core/src/main/resources/recipe_data.yaml
Labels: dependencies

#52 Filter recipe data
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/resources/recipe_data.yaml
Labels: developer, chore

#54 Drop recipe and integration module
  plugin-modernizer-integration/pom.xml
  plugin-modernizer-recipes/pom.xml
  pom.xml
Labels: chore

#57 Reproducible builds
  README.md
  pom.xml
Labels: documentation, chore
