Repository jenkins-infra/plugin-modernizer-tool, pull requests merged in 2024-09, with the labels that each got.

#246 Update root dockerfile with sdkman
  .gitpod/Dockerfile
  Dockerfile
  updatecli/updatecli.d/sdkman-temurin.yaml
Labels: chore

#247 Move plugin git directories to local cache
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/Main.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/MainTest.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/CacheManager.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/Plugin.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/SettingsEnvTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/model/PluginTest.java
Labels: enhancement

#249 Use JGit release
  pom.xml
Labels: dependencies

#256 Ensure to follow redirects
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/JsonUtils.java
Labels: bug

#257 Snakeyaml dependencyManagement
  pom.xml
Labels: dependencies

#258 chore(updatecli): Keep the main Dockerfile updated
  Dockerfile
  updatecli/updatecli.d/maven-install.yaml
  updatecli/updatecli.d/maven.yaml
Labels: chore

#262 Ensure to push updated refs
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
Labels: bug

#264 GitHub API update
  pom.xml
Labels: dependencies

#265 Fix typo on UpgradeToJava17 description
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
Labels: chore

#267 Prepare for github-api v2 and bump to 1.326
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/github/GHServiceTest.java
  pom.xml
Labels: dependencies, chore

#269 Distribute the CLI as a container
  .github/workflows/github-docker-registry-push.yml
  Dockerfile
  README.md
  scripts/import-maven-cache-macos.sh
  scripts/import-maven-cache.bat
  scripts/import-maven-cache.sh
Labels: enhancement, packaging

#274 feat(docker): Add a `aarch64` target
  .github/workflows/github-docker-registry-push.yml
  Dockerfile
Labels: enhancement, github_actions, packaging
