Repository jenkins-infra/plugin-modernizer-tool, pull requests merged in 2024-12, with the labels that each got.

#412 Don't distribute the CLI artifacts (like the far jar) to Artifactory
  plugin-modernizer-cli/pom.xml
Labels: chore

#413 Fix typos in JReleaser workflow
  .github/workflows/jreleaser.yaml
  jreleaser.yml
Labels: chore

#415 Do not display shutdown hook with some args
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/Main.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/MainTest.java
Labels: bug

#416 Refresh stats URL
  plugin-modernizer-core/src/main/resources/urls.properties
Labels: chore

#414 Add HomeBrew Formula template
  .gitignore
  homebrew/formula.rb.tpl
  jreleaser.yml
Labels: chore

#417 Rename parent-pom to pom
  plugin-modernizer-cli/pom.xml
  plugin-modernizer-core/pom.xml
  pom.xml
Labels: chore

#419 Run only one recipe per execution
  .gitpod/init.sh
  README.md
  docker-compose.yml
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/Main.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/MainTest.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Config.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/MavenInvoker.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtils.java
  plugin-modernizer-core/src/main/jte/commit.jte
  plugin-modernizer-core/src/main/jte/pr-body.jte
  plugin-modernizer-core/src/main/jte/pr-title.jte
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/ConfigTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/github/GHServiceTest.java
Labels: bug, enhancement

#418 Include build date on version
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/PomVersionProvider.java
  plugin-modernizer-cli/src/main/resources/pom.properties
  pom.xml
Labels: enhancement

#423 Split action (subcommands) and option
  README.md
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/Main.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/VersionProvider.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/BuildMetadataCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/ICommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/ListRecipesCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/RunCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/ValidateCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/converter/PluginConverter.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/converter/PluginFileConverter.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/converter/RecipeConverter.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/GlobalOptions.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/PluginOptions.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/MainTest.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Config.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/MavenInvoker.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/Plugin.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginService.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/github/GHServiceTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginServiceTest.java
Labels: enhancement

#424 Cleanup otherFiles on metadata
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataCollector.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/PluginMetadata.java
Labels: chore

#428 Handle push error
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/jte/pr-title-UpgradeNextMajorParentVersion.jte
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: bug, enhancement

#429 chore(updatecli): Automate URL update for plugin stats installations
  updatecli/updatecli.d/plugin-stats-url.yaml
Labels: maintenance, skip-changelog, dependencies, chore, updatecli, urls

#430 Use noreply email for committer
  README.md
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
Labels: bug, enhancement

#431 Add gson-api replacement
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
Labels: enhancement

#434 Update distribution URL and publish to homebrew
  .github/workflows/jreleaser.yaml
  homebrew/formula.rb.tpl
Labels: chore

#441 Fix workflow and update documentation for brew install
  .github/workflows/cd.yaml
  README.md
Labels: bug, documentation

#442 Fix publish workflow
  .github/workflows/cd.yaml
Labels: bug

#444 Restore tag name mandatory for release
  jreleaser.yml
Labels: bug

#449 GH_OWNER is now optional and got from token if set
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/ValidateCommand.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/github/GHServiceTest.java
Labels: chore

#446 Add our recipe model and remove OpenRewrite from CLI dependency
  plugin-modernizer-cli/pom.xml
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/DryRunCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/RunCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/converter/RecipeConverter.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Config.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataCollector.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataFlag.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataXmlTag.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/MavenInvoker.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/Recipe.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtils.java
  plugin-modernizer-core/src/main/jte/commit.jte
  plugin-modernizer-core/src/main/jte/pr-body.jte
  plugin-modernizer-core/src/main/jte/pr-title-UpgradeBomVersion.jte
  plugin-modernizer-core/src/main/jte/pr-title-UpgradeNextMajorParentVersion.jte
  plugin-modernizer-core/src/main/jte/pr-title-UpgradeParentVersion.jte
  plugin-modernizer-core/src/main/jte/pr-title-UpgradeToLatestJava11CoreVersion.jte
  plugin-modernizer-core/src/main/jte/pr-title-UpgradeToRecommendCoreVersion.jte
  plugin-modernizer-core/src/main/jte/pr-title.jte
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/ConfigTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/SettingsEnvTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/github/GHServiceTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/JsonUtilsTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: chore

#453 Update readme by using plugin-modernizer instead of jar
  README.md
Labels: documentation

#457 Bootstrap integration tests
  plugin-modernizer-cli/pom-it.xml
  plugin-modernizer-cli/pom.xml
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  pom.xml
Labels: tests

#458 Add integration test for validate command
  plugin-modernizer-cli/pom.xml
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/GlobalOptions.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Config.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/resources/urls.properties
Labels: tests

#461 Split global options
  README.md
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/Main.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/BuildMetadataCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/CleanupCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/DryRunCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/ICommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/ListRecipesCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/RunCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/ValidateCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/EnvOptions.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/GitHubOptions.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/GlobalOptions.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/IOption.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/PluginOptions.java
  plugin-modernizer-cli/src/main/resources/logback.xml
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Config.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/MavenInvoker.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/ConfigTest.java
Labels: chore

#462 Remove rewrite jenkins override
  pom.xml
Labels: chore

#467 Fix tests and comply with failsafe config
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
Labels: tests

#470 Add empty plugin as test resource
  .github/pull_request_template.md
  plugin-modernizer-cli/src/test/resources/empty/.github/CODEOWNERS
  plugin-modernizer-cli/src/test/resources/empty/.github/dependabot.yml
  plugin-modernizer-cli/src/test/resources/empty/.github/release-drafter.yml
  plugin-modernizer-cli/src/test/resources/empty/.github/workflows/jenkins-security-scan.yml
  plugin-modernizer-cli/src/test/resources/empty/.github/workflows/release-drafter.yml
  plugin-modernizer-cli/src/test/resources/empty/.gitignore
  plugin-modernizer-cli/src/test/resources/empty/.mvn/extensions.xml
  plugin-modernizer-cli/src/test/resources/empty/.mvn/maven.config
  plugin-modernizer-cli/src/test/resources/empty/Jenkinsfile
  plugin-modernizer-cli/src/test/resources/empty/LICENSE.md
  plugin-modernizer-cli/src/test/resources/empty/README.md
  plugin-modernizer-cli/src/test/resources/empty/pom.xml
  plugin-modernizer-cli/src/test/resources/empty/src/main/resources/index.jelly
Labels: tests

#463 Switch to SSH transport
  .gitignore
  .idea/.gitignore
  Jenkinsfile
  README.md
  plugin-modernizer-cli/pom.xml
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/BuildMetadataCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/ValidateCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/GitHubOptions.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/GlobalOptions.java
  plugin-modernizer-cli/src/main/resources/logback.xml
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/utils/GitHubServerContainer.java
  plugin-modernizer-cli/src/test/resources/a-fake-plugin/pom.xml
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Config.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/MavenInvoker.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginService.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/ConfigTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/github/GHServiceTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/model/PluginTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginServiceTest.java
  pom.xml
Labels: chore

#471 Use compress-api dependency
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
Labels: chore

#472 Fix null owner and change various logger
  Jenkinsfile
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/utils/GitHubServerContainer.java
  plugin-modernizer-cli/src/test/resources/logback-test.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataFlag.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
Labels: bug

#473 Override infra-bug template
  .github/ISSUE_TEMPLATE/1-report-bug.yml
Labels: documentation

#474 Restore and customize feature request
  .github/ISSUE_TEMPLATE/2-feature-request.yml
Labels: documentation

#478 Include version subcommand
  .github/ISSUE_TEMPLATE/1-report-bug.yml
  plugin-modernizer-cli/pom.xml
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/Main.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/VersionProvider.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/VersionCommand.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
Labels: chore

#486 Fix build process on aarch64 machines
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/JdkFetcher.java
  updatecli/updatecli.d/compress-api.yaml
  updatecli/updatecli.d/gson-api.yaml
Labels: bug

#489 Clean logs folder during clean
  pom.xml
Labels: chore

#490 Add JSON path API plugin to `recipes.yml`
  plugin-modernizer-cli/src/test/resources/replace-by-api-plugins/pom.xml
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
Labels: chore

#491 Skip conditional recipes
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
Labels: chore

#492 Add updatecli manifest to upgrade more plugins
  updatecli/updatecli.d/asm-api.yaml
  updatecli/updatecli.d/byte-buddy-api.yaml
  updatecli/updatecli.d/commons-lang3-api.yaml
  updatecli/updatecli.d/commons-text-api.yaml
  updatecli/updatecli.d/joda-time-api.yaml
  updatecli/updatecli.d/json-api.yaml
  updatecli/updatecli.d/json-path-api.yaml
Labels: chore

#493 Add condition isUsingBom
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsUsingBom.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsUsingBomTest.java
Labels: chore

#501 Git 2.47 for testcontainers
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/utils/GitHubServerContainer.java
Labels: tests

#509 Add some test for declarative recipes and some fixes
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/main/resources/versions.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: bug, tests

#510 Add condition for pom missing jenkins.baseline property
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsMissingJenkinsBaselineProperty.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsMissingJenkinsBaselinePropertyTest.java
Labels: chore

#511 Add updatecli manifest to keep parent plugin pom update to date
  updatecli/updatecli.d/plugin-pom.yaml
Labels: chore

#512 Add recipe to migrate to jenkins.baseline property
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/PluginMetadata.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/PomVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateToJenkinsBaseLineProperty.java
  plugin-modernizer-core/src/main/jte/pr-title-MigrateToJenkinsBaseLineProperty.jte
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/FetchMetadataTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateToJenkinsBaseLinePropertyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/JsonUtilsTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: chore

#513 Add visitor to add and remove a comment for properties and `jenkins.baseline` migration
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/PluginMetadata.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/Recipe.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateToJenkinsBaseLineProperty.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/visitors/AddBeforePropertyVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/visitors/AddPropertyCommentVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/visitors/RemovePropertyCommentVisitor.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateToJenkinsBaseLinePropertyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/AddBeforePropertyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/AddPropertyCommentVisitorTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/RemovePropertyCommentVisitorTest.java
Labels: enhancement

#516 Add is/missing common file conditional recipes and some cleanup
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/RecipesConsts.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/ArchetypeCommonFile.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/ArchetypeCommonFileVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataFinalizerVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/PomResolutionVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/Recipe.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsUsingArchetypeCommonFile.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/SetupDependabot.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateBomVersionVisitor.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/FetchMetadataTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsMissingBomTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsMissingJenkinsBaselinePropertyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsUsingArchetypeCommonFileTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsUsingBomTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateToJenkinsBaseLinePropertyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/SetupDependabotTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpgradeJenkinsVersionTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/AddBeforePropertyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/AddPropertyCommentVisitorTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/RemovePropertyCommentVisitorTest.java
  updatecli/updatecli.d/jenkins-bom.yaml
Labels: chore

#518 Add more tests
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/FetchMetadata.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/FetchMetadataTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: tests

#519 Avoid using String for a Path
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/ArchetypeCommonFile.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/PluginMetadata.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsUsingArchetypeCommonFile.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/SetupDependabot.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: bug, chore

#524 Add some recipes to add missing commons files
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: chore

#526 Clean and ensure JDK 17 for openrewrite
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
Labels: chore

#527 Add support for --plugin-path
  README.md
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/converter/PluginPathConverter.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/PluginOptions.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/Plugin.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/PomModifier.java
Labels: chore

#529 Fix order of property migrate and ensure it's validate with a test when a bom is added
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: chore

#528 Add recipe to remove release drafter if cd is present
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/ArchetypeCommonFile.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/RemoveReleaseDrafter.java
  plugin-modernizer-core/src/main/jte/pr-title-RemoveReleaseDrafter.jte
  plugin-modernizer-core/src/main/jte/pr-title-SetupDependabot.jte
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/RemoveReleaseDrafterTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/SetupDependabotTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: chore

#533 Add missing title for last java 8 update
  plugin-modernizer-core/src/main/jte/pr-title-UpgradeToLatestJava8CoreVersion.jte
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: chore

#522 chore(ga): Fix Docker build and integrate into release process
  .github/workflows/cd.yaml
  .github/workflows/github-docker-registry-push.yml
  .github/workflows/lint-workflows.yml
  Dockerfile
Labels: chore

#540 Use single classs imports
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/Main.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/PluginMetadata.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/FetchMetadata.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsUsingArchetypeCommonFile.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MetadataFinalizer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateToJenkinsBaseLineProperty.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/RemoveReleaseDrafter.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/SetupDependabot.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpdateBom.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpgradeJenkinsVersion.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginService.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/ConfigTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/SettingsEnvTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/github/GHServiceTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/impl/CacheManagerTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/model/PluginTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginServiceTest.java
Labels: chore

#541 Handle special case for analysis-pom-plugin parent
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/RecipesConsts.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/PomResolutionVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsUsingBom.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpdateBom.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateBomVersionVisitor.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/FetchMetadataTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsMissingBomTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsUsingBomTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpdateBomTest.java
Labels: chore

#542 Sign commits when ssh key is provided
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/utils/GitHubServerContainer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
Labels: chore

#544 Extract for info from Jenkinsfile and support different layout
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/JenkinsfileVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/PluginMetadata.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/CacheEntry.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/HealthScoreData.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/Platform.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/PlatformConfig.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/PluginInstallationStatsData.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/PluginVersionData.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/UpdateCenterData.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/FetchMetadata.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/FetchMetadataTest.java
Labels: enhancement, chore
