Repository jenkins-infra/plugin-modernizer-tool, pull requests merged in 2024-11, with the labels that each got.

#374 Update UpgradeToJava17 by setting LTS instead of weekly
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
Labels: enhancement

#375 Change org.kohsuke.stapler.StaplerRequest to org.kohsuke.stapler.StaplerRequest2
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
Labels: enhancement

#385 chore: fix tooling following the GitHub organization change from `jenkinsci` to `jenkins-infra`
  .github/CODEOWNERS
  .github/workflows/updatecli.yaml
  README.md
  plugin-modernizer-core/src/main/jte/pr-body.jte
  pom.xml
  updatecli/values.github-action.yaml
Labels: chore, updatecli

#387 Rewrite bom upgrade and fix dependency management
  pom.xml
Labels: dependencies

#403 Add PR checklist template
  .github/.github/pull_request_template.md
Labels: chore
