Repository jenkins-infra/plugin-modernizer-tool, pull requests merged in 2024-07, with the labels that each got.

#63 Extract maven rewrite plugin to properties from pom
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/MavenInvoker.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/main/resources/versions.properties
  pom.xml
Labels: enhancement

#64 Maven version validation
  README.md
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/MavenInvoker.java
  pom.xml
Labels: enhancement

#70 Fix checkstyle import
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
Labels: chore

#72 Remove redundant files and lines
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/test/resources/recipe_data.json
Labels: chore

#71 Use RecipeDescriptor instead of raw Jackson
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/MavenInvoker.java
Labels: chore

#78 Use Paths instead of File
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/MavenInvoker.java
Labels: chore

#79 Reduce some debug logs
  plugin-modernizer-cli/src/main/resources/logback.xml
Labels: chore

#84 Cleanup logs and rename some private methods
  plugin-modernizer-cli/src/main/resources/logback.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
Labels: chore

#87 Fetch SCM URL from UC
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/UpdateCenterData.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/JenkinsPluginInfo.java
  plugin-modernizer-core/src/main/resources/update_center.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/JenkinsPluginInfoTest.java
Labels: enhancement

#109 Extract github client to member and move local vars
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
Labels: chore

#128 1 - Remove checkstyle will be replaced by spotless
  .mvn/checkstyle.xml
  plugin-modernizer-cli/pom.xml
  plugin-modernizer-core/pom.xml
  pom.xml
Labels: chore

#129 2 - Enable spotless and reformat
  plugin-modernizer-cli/pom.xml
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/CommaSeparatedParameterConsumer.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/Main.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/PluginLoggerDiscriminator.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/PomVersionProvider.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommaSeparatedParameterConsumerTest.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/ConsoleLogFilterTest.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/MainTest.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/PluginLoggerDiscriminatorTest.java
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Config.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataCollector.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/PluginMetadata.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/CacheManager.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/MavenInvoker.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/UpdateCenterData.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/JenkinsPluginInfo.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginListParser.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/ConfigTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataCollectorTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/impl/CacheManagerTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/JenkinsPluginInfoTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginListParserTest.java
  pom.xml
Labels: chore

#131 Add declarative recipes using supported yaml OpenRewrite format
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/Main.java
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/MavenInvoker.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/RecipeDescriptor.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/main/resources/recipe_data.yaml
Labels: enhancement

#133 Cleanup configuration-as-code.version when adding bom
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
Labels: enhancement

#136 Exclude artifact from rewrite jenkins to test newer versions
  plugin-modernizer-core/pom.xml
  pom.xml
Labels: dependencies, chore
