Repository jenkins-infra/plugin-modernizer-tool, pull requests merged in 2025-03, with the labels that each got.

#837 Update Recipe Migrate Acegi Security To Spring Security
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateAcegiSecurityToSpringSecurity.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateAcegiSecurityToSpringSecurityTest.java
Labels: enhancement

#515 Support for scoop distribution
  .github/workflows/cd.yaml
  jreleaser.yml
Labels: enhancement

#860 Jackson and rewrite bom update
  pom.xml
Labels: dependencies

#868 Baseline 2.462 was removed from bom
  .github/workflows/updatecli.yaml
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/resources/versions.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpgradeJenkinsVersionTest.java
  pom.xml
Labels: enhancement, tests, dependencies

#870 chore: add documentation about how to install the tool via scoop
  README.md
Labels: documentation

#884 com.gargoylesoftware.htmlunit replaced to org.htmlunit in UpgradeNextMajorParentVersion
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: enhancement

#900 Update bom and asm api
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/main/resources/versions.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/ReplaceLibrariesWithApiPluginTest.java
Labels: dependencies
