Repository jenkins-infra/plugin-modernizer-tool, pull requests merged in 2025-04, with the labels that each got.

#899 Add Annotate With Jenkins recipe under migration to junit5
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/AnnotateWithJenkins.java
  plugin-modernizer-core/src/main/jte/pr-body-MigrateToJUnit5.jte
  plugin-modernizer-core/src/main/jte/pr-title-MigrateToJUnit5.jte
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/AnnotateWithJenkinsTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: enhancement

#911 Update asm-api and fix placeholder
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/main/resources/versions.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/ReplaceLibrariesWithApiPluginTest.java
Labels: dependencies, chore

#922 Cleanup - Remove full stop from PR title and add comments in tests
  plugin-modernizer-core/src/main/jte/pr-title-MergeGitIgnoreRecipe.jte
  plugin-modernizer-core/src/main/jte/pr-title-UpdateScmUrl.jte
  plugin-modernizer-core/src/main/jte/pr-title-UpgradeNextMajorParentVersion.jte
  plugin-modernizer-core/src/main/jte/pr-title-UpgradeToRecommendCoreVersion.jte
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/AddDetachedPluginDependencyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateAcegiSecurityToSpringSecurityTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateStaplerAndJavaxToJakartaTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: chore

#934 Fix bug to not to add duplicate super call in Migrate Acegi Security To Spring Security recipe
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateAcegiSecurityToSpringSecurity.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateAcegiSecurityToSpringSecurityTest.java
Labels: bug

#915 Add precondition to not apply the MigrateToJUnit5 recipe on files using JenkinsSessionRule field type.
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
Labels: enhancement

#952 Recipe - Migrate from com.github.tomakehurst to org.wiremock
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateTomakehurstToWiremock.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/main/resources/versions.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateTomakehurstToWiremockTest.java
Labels: enhancement

#963 Fix incremental bom test and update jenkins parent version to 5.12
  plugin-modernizer-core/src/main/resources/versions.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpdateBomTest.java
Labels: tests, dependencies

#955 Test coverage for MigrateTomakehurstToWiremock recipe
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: tests

#964 Update github-api to 2.0-rc.3
  pom.xml
Labels: dependencies

#975 Group several update and fix tests
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/resources/versions.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateTomakehurstToWiremockTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpdateBomTest.java
  pom.xml
Labels: tests, dependencies

#979 Standalone Migration from Tomakehurst to WireMock Recipe
  plugin-modernizer-core/src/main/jte/pr-body-MigrateTomakehurstToWiremock.jte
  plugin-modernizer-core/src/main/jte/pr-title-MigrateTomakehurstToWiremock.jte
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
Labels: chore
