Repository jenkins-infra/plugin-modernizer-tool, pull requests merged in 2025-01, with the labels that each got.

#546 Handle more identifier on Jenkinsfile
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/JenkinsfileVisitor.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/FetchMetadataTest.java
Labels: chore

#550 Remove relativePath precondition
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/PreconditionError.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/EnsureRelativePath.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/EnsureRelativePathTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/PomModifierTest.java
Labels: chore

#551 Fix some regression for outdated plugin and add tests for fetch metadata
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-cli/src/test/resources/jenkins-1.5/.gitignore
  plugin-modernizer-cli/src/test/resources/jenkins-1.5/pom.xml
  plugin-modernizer-cli/src/test/resources/jenkins-1.5/src/main/resources/index.jelly
  plugin-modernizer-cli/src/test/resources/jenkins-1.6/.gitignore
  plugin-modernizer-cli/src/test/resources/jenkins-1.6/pom.xml
  plugin-modernizer-cli/src/test/resources/jenkins-1.6/src/main/resources/index.jelly
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/Plugin.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/PomModifier.java
Labels: chore

#555 Use YAML path to avoid hard-coding plugin API version on tests
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: tests

#558 Made `EnsureRelativePath` a top level recipe
  plugin-modernizer-core/src/main/jte/pr-title-EnsureRelativePath.jte
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: chore

#565 Fix one test with hardcoded bom version
  plugin-modernizer-core/src/main/resources/versions.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: tests

#566 Only add space on empty relativePath tag if still using maven release plugin
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/EnsureRelativePath.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/EnsureRelativePathTest.java
Labels: chore

#567 Do not remove property if still referenced
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/RemoveProperty.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/RemovePropertyTest.java
Labels: chore

#568 Fix possible nullpointer if the maven version cannot be read
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/MavenInvoker.java
Labels: chore

#569 fix(ga): Fixes permissions for package upload.
  .github/workflows/cd.yaml
Labels: chore

#560 Updates SCM URLs in POM files from git:// to https:// protocol.
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpdateScmUrl.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateScmUrlVisitor.java
  plugin-modernizer-core/src/main/jte/pr-title-UpdateScmUrl.jte
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpdateScmUrlTest.java
Labels: chore

#571 Add recipe for index.jelly and to replace a test constructor on outdated plugin
  plugin-modernizer-cli/pom.xml
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/EnsureIndexJelly.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/code/ReplaceRemovedSSHLauncherConstructor.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/EnsureIndexJellyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/code/ReplaceRemovedSSHLauncherConstructorTest.java
Labels: enhancement

#573 Fix --plugin-path when running with run command and support default value
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/BuildMetadataCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/DryRunCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/RunCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/PluginOptions.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
Labels: chore

#574 Lower one log level
  plugin-modernizer-cli/src/main/resources/logback.xml
Labels: chore

#576 Fix broken links
  README.md
Labels: documentation

#579 Auto-completion
  README.md
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/Main.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/DryRunCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/RunCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/converter/RecipeConverter.java
Labels: enhancement

#582 Fix #581 (default plugin-path) and implement basic test for PluginOptions
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/PluginOptions.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/options/PluginOptionsTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/github/GHServiceTest.java
Labels: tests, chore

#583 Avoid hardcoding implicit JDK and workarround #580
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/JenkinsfileVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/JDK.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/StaticPomParser.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/FetchMetadataTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/model/JDKTest.java
Labels: chore

#584 Fix missing title for SetupGitIgnore recipe
  plugin-modernizer-core/src/main/jte/pr-title-SetupGitIgnore.jte
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: chore

#588 Upgrade version property if used for bom
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateBomVersionVisitor.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpdateBomTest.java
Labels: bug

#589 Add unit test coverage for options
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/EnvOptions.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/GlobalOptions.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/options/EnvOptionsTest.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/options/GlobalOptionsTest.java
Labels: tests

#590 Use value of gitHubRepo for local plugin if present
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/StaticPomParser.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginServiceTest.java
Labels: chore

#591 Ignore coverage for generated template classes
  pom.xml
Labels: chore

#603 Update command in README.md
  README.md
Labels: documentation

#585 Add `MergeGitIgnoreRecipe` to merge existing .gitignore file with common entries
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java
  plugin-modernizer-core/src/main/jte/pr-title-MergeGitIgnoreRecipe.jte
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipeTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: chore

#606 fix(jte): Use conventional commit for the title, and create a custom body for this recipe.
  plugin-modernizer-core/src/main/jte/pr-body-UpgradeToLatestJava11CoreVersion.jte
  plugin-modernizer-core/src/main/jte/pr-title-UpgradeToLatestJava11CoreVersion.jte
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: chore

#612 Cleanup and fix tests
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsMissingBom.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsMissingJenkinsBaselineProperty.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/main/resources/versions.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsMissingBomTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsMissingJenkinsBaselinePropertyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/RemovePropertyTest.java
  pom.xml
Labels: chore

#604 Add a Java ISO visitor for metadata collection
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/JavaFileVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataFinalizerVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/PluginMetadata.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/FetchMetadataTest.java
Labels: chore

#613 Demonstrate test for #580
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/FetchMetadataTest.java
Labels: tests

#615 Reduce build time by skipping by default slow integration tests and use JUnit 5 Parallel execution for some classes
  plugin-modernizer-cli/pom.xml
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-cli/src/test/resources/junit-platform.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/ConfigTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/SettingsEnvTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/SettingsHomeDirTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/SettingsUserDirTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/FetchMetadataTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/github/GHServiceTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/model/JDKTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/model/PluginTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/EnsureIndexJellyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/EnsureRelativePathTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsUsingArchetypeCommonFileTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/IsUsingBomTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateToJenkinsBaseLinePropertyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/RemovePropertyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/RemoveReleaseDrafterTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/SetupDependabotTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpdateBomTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpdateScmUrlTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpgradeJenkinsVersionTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/code/ReplaceRemovedSSHLauncherConstructorTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/JsonUtilsTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginServiceTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/AddBeforePropertyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/AddPropertyCommentVisitorTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/RemovePropertyCommentVisitorTest.java
  plugin-modernizer-core/src/test/resources/junit-platform.properties
Labels: tests

#619 Handle local plugin without incrementals and gitHubRepo property
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/StaticPomParser.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginServiceTest.java
Labels: chore

#620 Support multiple file path for archetype pattern
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/ArchetypeCommonFile.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/ArchetypeCommonFileVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/RemoveReleaseDrafter.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/FetchMetadataTest.java
Labels: chore

#621 Skip some test from IDE due to environment mocking that require several surefire execution
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/SettingsEnvTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/SettingsHomeDirTest.java
Labels: chore

#623 Render commit message and unique branch name
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtils.java
  plugin-modernizer-core/src/main/jte/branch.jte
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: enhancement

#624 fix(doc): Add a GitPod section.
  README.md
Labels: documentation

#632 Start implementation of UpdateJenkinsFileVisitor
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/code/ReplaceRemovedSSHLauncherConstructor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateJenkinsFileVisitor.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateJenkinsFileVisitorTest.java
Labels: chore

#634 Insert comments and configuration on `buildPlugin`
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/PlatformConfig.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateJenkinsFileVisitor.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateJenkinsFileVisitorTest.java
Labels: chore

#639 Add more test for UpdateJenkinsFileVisitor and ensure to cleanup unused variables
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateJenkinsFileVisitor.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateJenkinsFileVisitorTest.java
Labels: chore

#640 Handle `buildPlugin` parameters update
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateJenkinsFileVisitor.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateJenkinsFileVisitorTest.java
Labels: chore

#636 Added Instructions to Configure SSH keys
  README.md
Labels: documentation

#618 Fix `MergeGitIgnoreRecipe` recipe
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipeTest.java
Labels: chore

#607 Storing logs close to the sources
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/ConsoleLogFilter.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/Main.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/PluginLoggerDiscriminator.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/BuildMetadataCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/CleanupCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/DryRunCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/ListRecipesCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/RunCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/ValidateCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/VersionCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/GlobalOptions.java
  plugin-modernizer-cli/src/main/resources/logback.xml
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/ConsoleLogFilterTest.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/PluginLoggerDiscriminatorTest.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/options/GlobalOptionsTest.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Config.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/Plugin.java
Labels: chore

#649 More skip verification
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
Labels: enhancement

#650 Fix broken tests
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
Labels: tests

#652 Spotless
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
Labels: chore

#655 Fixed the issue of Trailing slashes being duplicated
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipe.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MergeGitIgnoreRecipeTest.java
Labels: chore

#658 Fix invalid PR name for updatecli
  updatecli/updatecli.d/commons-text-api.yaml
  updatecli/updatecli.d/json-path-api.yaml
Labels: chore

#668 Do not use `ExecutionContext` messaging
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataExecutionContext.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataFinalizerVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataVisitor.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/FetchMetadata.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MetadataFinalizer.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/FetchMetadataTest.java
  pom.xml
Labels: enhancement

#674 Fix RemoveReleaseDrafter CD detection
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/RemoveReleaseDrafter.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/RemoveReleaseDrafterTest.java
Labels: chore

#677 Added homebrew installation step in README.md
  README.md
Labels: documentation

#683 Enable fixed test testWithJenkinsfileOnlyShebangAndComment
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/FetchMetadataTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateJenkinsFileVisitorTest.java
Labels: tests

#685 Use 2.462.3 for recommended version
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: chore

#687 Implemented GitHub actions
  .github/actions/modernizer-action/action.yml
  .github/workflows/test-modernizer-action.yml
Labels: chore

#679 Uses the detected JDK to use the right values in Jenkinsfile. #598
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/JDK.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/CreateJenkinsFile.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/CreateJenkinsFileTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: chore

#697 Return GHUser class when a GitHub action is detected
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
Labels: bug

#694 Update PR body for SetupJenkinsfile since now we insert the correct JDK
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/JDK.java
  plugin-modernizer-core/src/main/jte/pr-body-SetupJenkinsfile.jte
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/model/JDKTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/CreateJenkinsFileTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: chore

#698 fix(jte): Adding dependabot also increases the Plugin Health Score.
  plugin-modernizer-core/src/main/jte/pr-body-SetupDependabot.jte
Labels: chore

#701 Enhance the test action workflow and run againts the empty plugin
  .github/workflows/test-modernizer-action.yml
Labels: chore

#708 Fix some tests and group bom update
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/resources/versions.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpgradeJenkinsVersionTest.java
Labels: bug, tests

#715 Ensure old bom version can be upgraded
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/RecipesConsts.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateBomVersionVisitor.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: chore

#713 Enforce LTS version
  pom.xml
Labels: chore

#716 Add modified files to Plugin
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/Plugin.java
Labels: chore

#719 Run tests FetchMetadataTest concurrent
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataExecutionContext.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/PluginMetadata.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/FetchMetadata.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/FetchMetadataTest.java
Labels: tests

#721 Improve integration test for force-push and remove some warnings related to Maven and WireMock
  plugin-modernizer-cli/pom-it.xml
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/utils/GitHubServerContainer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
Labels: tests

#720 Setup Jenkinsfile on common recipes
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/CreateJenkinsFile.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/CreateJenkinsFileTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: chore

#722 A bit more test optimization
  plugin-modernizer-cli/pom-it.xml
  plugin-modernizer-cli/src/test/resources/junit-platform.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/SettingsEnvTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/SettingsHomeDirTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/config/SettingsUserDirTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/Utils.java
  plugin-modernizer-core/src/test/resources/junit-platform.properties
Labels: tests

#728 Run PluginServiceTest concurrently
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/CSVUtils.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginServiceTest.java
Labels: tests

#740 Only fork repo when there is changes done by the recipe
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/github/GHServiceTest.java
Labels: chore

#743 Add commons-compress-api.version into versions.properties
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/resources/versions.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  updatecli/updatecli.d/compress-api.yaml
Labels: chore

#744 Fix invoker.logs path for junit-attachement
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
Labels: tests

#745 Add more API version to versions.properties
  plugin-modernizer-core/src/main/resources/versions.properties
Labels: chore

#746 Update API versions on versions.properties using updatecli
  plugin-modernizer-core/src/main/resources/versions.properties
  updatecli/updatecli.d/asm-api.yaml
  updatecli/updatecli.d/byte-buddy-api.yaml
  updatecli/updatecli.d/commons-lang3-api.yaml
  updatecli/updatecli.d/commons-text-api.yaml
  updatecli/updatecli.d/gson-api.yaml
  updatecli/updatecli.d/joda-time-api.yaml
  updatecli/updatecli.d/json-api.yaml
  updatecli/updatecli.d/json-path-api.yaml
Labels: chore

#752 Add updatecli manifest to keep jenkins-test-harness updated
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  updatecli/updatecli.d/jenkins-test-harness.yaml
Labels: chore

#755 Add yaml files on declarative tests. Use getJenkinsTestHarnessVersio() when possible
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpgradeJenkinsTestHarnessVersion.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: chore
