Repository jenkins-infra/plugin-modernizer-tool, pull requests merged in 2025-08, with the labels that each got.

#1189 Reference to the new metadata repo
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/utils/GitHubServerContainer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/github/GHServiceTest.java
Labels: enhancement

#1191 Add recipe Migrate Commons Lang2 To Lang3 And CommonText
  plugin-modernizer-core/src/main/jte/pr-body-MigrateCommonsLang2ToLang3AndCommonText.jte
  plugin-modernizer-core/src/main/jte/pr-title-MigrateCommonsLang2ToLang3AndCommonText.jte
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: chore

#1216 Fix metadata validation addressing rpuBaseline
  scripts/validate_metadata.py
Labels: chore

#1222 Store the opt out repositories and add option to override this behaviour
  README.md
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/command/RunCommand.java
  plugin-modernizer-cli/src/main/java/io/jenkins/tools/pluginmodernizer/cli/options/EnvOptions.java
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/options/EnvOptionsTest.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Config.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/CacheManager.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/OptOutPluginsData.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/PluginService.java
  plugin-modernizer-core/src/main/resources/urls.properties
Labels: chore

#1235 Jammy to Noble
  Dockerfile
  updatecli/updatecli.d/maven.yaml
Labels: dependencies
