Repository jenkins-infra/plugin-modernizer-tool, pull requests merged in 2025-05, with the labels that each got.

#991 Group jenkins component update
  plugin-modernizer-core/src/main/resources/versions.properties
  updatecli/updatecli.d/jenkins-bom.yaml
  updatecli/updatecli.d/jenkins-test-harness.yaml
  updatecli/updatecli.d/jenkins-updates.yaml
  updatecli/updatecli.d/plugin-pom.yaml
Labels: dependencies, chore

#997 Recipe to Replace Deprecated IOException2
  plugin-modernizer-core/src/main/jte/pr-body-ReplaceIOException2WithIOException.jte
  plugin-modernizer-core/src/main/jte/pr-title-ReplaceIOException2WithIOException.jte
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: enhancement

#1018 Upgrade to latest OpenRewrite
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/AddThrowsExceptionWhereAssertThrows.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/AnnotateWithJenkins.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateAcegiSecurityToSpringSecurity.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpgradeJenkinsTestHarnessVersion.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  pom.xml
Labels: dependencies
