Repository jenkins-infra/plugin-modernizer-tool, pull requests merged in 2025-02, with the labels that each got.

#759 Scanning recipe to add dependency on detached plugin
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/DetachedPlugins.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/AddDetachedPluginDependency.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/AddDetachedPluginDependencyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: enhancement

#761 GSON update to 2.12.1
  pom.xml
Labels: dependencies

#762 Include jenkins.core.minimum.version on pom
  pom.xml
Labels: skip-changelog

#764 Filter jenkins.core.minimum.version and updatecli update it on the pom.xml
  plugin-modernizer-core/src/main/resources/versions.properties
  updatecli/updatecli.d/jenkins-lts.yaml
Labels: chore

#765 Fix incompatibility for OpenRewrite and jackson-dataformat-yaml
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
  plugin-modernizer-cli/src/test/resources/logback-test.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/PluginMetadata.java
  pom.xml
Labels: bug

#768 Fix typo on log name
  plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/CommandLineITCase.java
Labels: skip-changelog

#774 Scanning recipe to check ChartUtil is used or not when migrating to Stapler2 and Javax to Jakarta
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateStaplerAndJavaxToJakarta.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateStaplerAndJavaxToJakartaTest.java
Labels: chore

#775 Delete legacy PRs
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/github/GHServiceTest.java
Labels: chore

#776 Recipe filtering
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: chore

#777 Fix getting minimal LTS version
  updatecli/scripts/jenkins-lts.sh
  updatecli/updatecli.d/jenkins-lts.yaml
Labels: chore

#778 Top level recipe to Remove <developers> tag
  plugin-modernizer-core/src/main/jte/pr-body-RemoveDevelopersTag.jte
  plugin-modernizer-core/src/main/jte/pr-title-RemoveDevelopersTag.jte
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: enhancement

#779 Bump rewrite deps
  pom.xml
Labels: dependencies

#780 Fix possible nullpointer if jenkinsVersion is null
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/JDK.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/model/JDKTest.java
Labels: bug

#783 Add meaningful message when default branch was removed but not present on local directory
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
Labels: chore

#784 Add jsoup API plugin
  plugin-modernizer-cli/src/test/resources/replace-by-api-plugins/pom.xml
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/main/resources/versions.properties
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
Labels: chore

#785 Add jsoup manifests
  updatecli/updatecli.d/jsoup.yaml
Labels: chore

#786 Add jsoup friendly PR title and body
  plugin-modernizer-core/src/main/jte/pr-body-UseJsoupApiPlugin.jte
  plugin-modernizer-core/src/main/jte/pr-title-UseJsoupApiPlugin.jte
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
Labels: enhancement

#791 Move recipe Replace Libraries With Api Plugin
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/ReplaceLibrariesWithApiPlugin.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/ReplaceLibrariesWithApiPluginTest.java
Labels: chore

#810 Fix test due to remove incrementals
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpdateBomTest.java
Labels: tests

#819 Fix tests
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/UpdateBomTest.java
Labels: tests

#825 fix(recipes): update UpgradeNextMajorParentVersion recipe Jenkins version to 2.479.3
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/model/JDKTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateToJenkinsBaseLinePropertyTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/JsonUtilsTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/utils/TemplateUtilsTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/visitors/UpdateJenkinsFileVisitorTest.java
Labels: enhancement

#808 Recipe to Migrate Acegi Security to Spring Security
  plugin-modernizer-core/pom.xml
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateAcegiSecurityToSpringSecurity.java
  plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateStaplerAndJavaxToJakarta.java
  plugin-modernizer-core/src/main/resources/META-INF/rewrite/recipes.yml
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/DeclarativeRecipesTest.java
  plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/recipes/MigrateAcegiSecurityToSpringSecurityTest.java
Labels: chore
